<%@ Page Language="C#" AutoEventWireup="True" CodeBehind="Default.aspx.cs" Inherits="Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <telerik:RadStyleSheetManager id="RadStyleSheetManager1" runat="server" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous" />
</head>
<body>
    <form id="form1" runat="server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
        <Scripts>
            <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js" />
            <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js" />
            <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js" />
        </Scripts>
    </telerik:RadScriptManager>
    <script type="text/javascript">
        //Put your JavaScript code here.
    </script>

    <%-- ADDED LINK ON THIS PAGE FOR EASY ACCESS TO SECOND PAGE --%>
    <div><a href="SpaceXData.aspx" class="btn btn-primary">SpaceXData</a></div>


    <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
            <AjaxSettings>
                            <telerik:AjaxSetting AjaxControlID="BookNowCloseButton">
                        <UpdatedControls>
                            <telerik:AjaxUpdatedControl ControlID="RadGrid1" />
                        </UpdatedControls>
                    </telerik:AjaxSetting>
                    <telerik:AjaxSetting AjaxControlID="RefreshButton">
                        <UpdatedControls>
                            <telerik:AjaxUpdatedControl ControlID="RadGrid1" />
                        </UpdatedControls>
                    </telerik:AjaxSetting>
                    <telerik:AjaxSetting AjaxControlID="RadGrid1">
                        <UpdatedControls>
                            <telerik:AjaxUpdatedControl ControlID="RadGrid1" />
                        </UpdatedControls>
                    </telerik:AjaxSetting>
                </AjaxSettings>
    </telerik:RadAjaxManager>
    <div>

    </div>
       
        <telerik:RadGrid ID="RadGrid1" runat="server" AllowAutomaticDeletes="True" AllowAutomaticInserts="True" AllowAutomaticUpdates="True" AllowFilteringByColumn="True" AllowMultiRowSelection="True" 
            AllowSorting="True" AutoGenerateDeleteColumn="True" DataSourceID="SqlDataSource1" Skin="Black" OnInsertCommand="RadGrid1_InsertCommand" CellSpacing="-1" GridLines="Both">
  
        <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
            <MasterTableView AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" CommandItemDisplay="Top">
                <Columns>
                    <telerik:GridBoundColumn DataField="Id" DataType="System.Int32" FilterControlAltText="Filter Id column" HeaderText="Id" ReadOnly="True" SortExpression="Id" UniqueName="Id" Visible="False">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="FirstName" FilterControlAltText="Filter FirstName column" HeaderText="FirstName" SortExpression="FirstName" UniqueName="FirstName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="LastName" FilterControlAltText="Filter LastName column" HeaderText="LastName" SortExpression="LastName" UniqueName="LastName">
                    </telerik:GridBoundColumn>
                    <telerik:GridTemplateColumn DataField="Chocolate" DataType="System.Boolean" FilterControlAltText="Filter Chocolate column" HeaderText="Chocolate" SortExpression="Chocolate" UniqueName="Chocolate">
                        <InsertItemTemplate>
                            <asp:CheckBox ID="CheckBox1" runat="server" Skin="Black"/>
                        </InsertItemTemplate>
                        <HeaderTemplate>
                            <telerik:RadCheckBox ID="RadCheckBox4" runat="server" Checked='<%# Bind("Chocolate") %>' Skin="Black">
                            </telerik:RadCheckBox>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <telerik:RadCheckBox ID="RadCheckBox3" runat="server" OnCheckedChanged="CheckChanged" Checked='<%# Bind("Chocolate") %>' Skin="Black">
                            </telerik:RadCheckBox>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>
                    <telerik:GridTemplateColumn DataField="PreferredColors" FilterControlAltText="Filter PreferredColors column" HeaderText="PreferredColors" SortExpression="PreferredColors" UniqueName="PreferredColors">
                            <InsertItemTemplate>
                                <telerik:RadComboBox ID="RadComboBox1" Runat="server" CheckBoxes="True" Skin="Black">
                                    <Items>
                                        <telerik:RadComboBoxItem runat="server" Text="Blue" Value="Blue" />
                                        <telerik:RadComboBoxItem runat="server" Text="Green" Value="Green" />
                                        <telerik:RadComboBoxItem runat="server" Text="Red" Value="Red" />
                                        <telerik:RadComboBoxItem runat="server" Text="Purple" Value="Purple" />
                                        <telerik:RadComboBoxItem runat="server" Text="Yellow" Value="Yellow" />
                                    </Items>
                                </telerik:RadComboBox>
                           </InsertItemTemplate>       
                            <ItemTemplate>
                                <telerik:RadLabel ID="RadLabel1" runat="server" Skin="Black" Text='<%# Bind("PreferredColors") %>'>
                                </telerik:RadLabel>
                            </ItemTemplate>
                         <FilterTemplate>
                                    <telerik:RadComboBox RenderMode="Lightweight" ID="ColorFilter" Width="90px" SelectedValue='<%# ((GridItem)Container).OwnerTableView.GetColumn("PreferredColors").CurrentFilterValue %>'
                                        runat="server" OnClientSelectedIndexChanged="PreferredColorsChanged">
                                        <Items>
                                            <telerik:RadComboBoxItem Text="All" Value="" />
                                            <telerik:RadComboBoxItem Text="Blue" Value="Blue" />
                                            <telerik:RadComboBoxItem Text="Green" Value="Green" />
                                            <telerik:RadComboBoxItem Text="Red" Value="Red" />
                                            <telerik:RadComboBoxItem Text="Purple" Value="Purple" />
                                            <telerik:RadComboBoxItem runat="server" Text="Yellow" Value="Yellow" />
                                        </Items>
                                    </telerik:RadComboBox>
                                    <telerik:RadScriptBlock ID="RadScriptBlock4" runat="server">
                                        <script type="text/javascript">
                                            function PreferredColorsChanged(sender, args) {
                                                var tableView = $find("<%# ((GridItem)Container).OwnerTableView.ClientID %>");
                                            tableView.filter("PreferredColors", args.get_item().get_value(), "Contains");
                                        }
                                        </script>
                                    </telerik:RadScriptBlock>
                                </FilterTemplate>
                    </telerik:GridTemplateColumn>
                </Columns>
            </MasterTableView>
        </telerik:RadGrid>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT [Id], [FirstName], [LastName], [Chocolate], [PreferredColors] FROM [PatientInfo] ORDER BY LastName"
           DeleteCommand="DELETE FROM [PatientInfo] WHERE [Id] = @Id">
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32"/>
                </DeleteParameters>
        </asp:SqlDataSource>
       
    </form>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>
